# Generated by Django 4.2.7 on 2024-02-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images'),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('date', 'title', 'location')},
        ),
    ]
